### ISSUE TITLE
Natural Selection doesn't appear to build on phettest

### ISSUE THREAD

**Issue by samreid** [phetsims/phetmarks#52]
Today @KatieWoe pointed out that pressing "Build" on natural-selection on phettest says "kicking off a build" but then it doesn't build.  It also doesn't clean, and the served built file is 3 weeks old.  Could it be a caching problem?  @zepumph or @jonathanolson how can we investigate?

**Comment by zepumph** [comment]
The Old phettest server would let you kick off a built, and then wait around until it was finished. That meant that a request was held up until completion, perhaps a couple of minutes. This was fine because it was only internal and on its own domain. The new phettest runs through a portion of PhET/CUs network that has a similar route to other, more important requests, and so we weren't able to allow these build requests to hang out until completion. Thus, the "build" button is now a "kick off a build" instead of a "building". There is no feedback on the build unfortunately. Note conversation around https://github.com/phetsims/special-ops/issues/170#issuecomment-709658217. 

For this particular case it seems like something is wrong on phettest, I can take a look to see specifically why NS isn't building.


Note that this behavior is the same for all slow grunt commands, like pull all and "refresh perennial" too.

**Comment by zepumph** [comment]
I tried to refresh perennial, and saw an error on phettest. So I just went onto bayes.

I went to /data/web/htdocs//dev/phettest/ as the README in phetmarks/phettest told me to. In perennial I pulled, cloned, and npm prune/updated. and then was able to build NS successfully. I then "kicked off" the build on phettest and all looked good.

**Comment by zepumph** [comment]
My main guess as to the root cause of this is that perennial needed refreshing. See https://github.com/phetsims/phetmarks/issues/53. Anything else here @samreid?

**Comment by samreid** [comment]
That is a reasonable hypothesis.  @KatieWoe can you please test that phettest builds are working as expected?

**Comment by KatieWoe** [comment]
Natural Selection at least seems to build properly

**Comment by samreid** [comment]
Thanks, closing.
